import './globals.css'
import type { Metadata } from 'next'
import { Baloo_2 } from 'next/font/google'
import Navbar from '../components/navbar'
import Providers from '../components/providers'
import Sidebar from '../components/Sidebar'
import ClientComponent from '../components/renderChildrenClient'


const baloo = Baloo_2({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode,
  session: any
}) {

  return (
    <html lang="en">
      <body className={baloo.className}>
       <Providers session={session}>
          <Navbar />
          <Sidebar />
          <ClientComponent>{children}</ClientComponent>
        </Providers>
      </body>
    </html>
  )
}
